# Generated by Django 5.2.4 on 2025-07-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
