# Generated by Django 5.2.4 on 2025-07-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('submit', models.CharField(default='Submit', max_length=25)),
            ],
            options={
                'verbose_name': 'Help Topic',
                'verbose_name_plural': 'Help Topics',
            },
        ),
    ]
