# Generated by Django 5.2.4 on 2025-07-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='submit',
            field=models.CharField(max_length=25),
        ),
    ]
